[[redirects]]
  from = "/gym/*"
  to = "https://oracleapex.com/ords/r/medimatrics/royal-gym/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/gym"
  to = "https://oracleapex.com/ords/r/medimatrics/royal-gym/login"
  status = 200
  force = true

[[redirects]]
  from = "/pos/*"
  to = "https://oracleapex.com/ords/r/pos-shop/pos/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/pos"
  to = "https://oracleapex.com/ords/r/pos-shop/pos/login"
  status = 200
  force = true

[[redirects]]
  from = "/erp/*"
  to = "https://oracleapex.com/ords/r/yarn_oracle/ag-traders/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/erp"
  to = "https://oracleapex.com/ords/r/yarn_oracle/ag-traders/login"
  status = 200
  force = true

[[redirects]]
  from = "/hms/*"
  to = "https://oracleapex.com/ords/r/medimatrics/medimatrics/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/hms"
  to = "https://oracleapex.com/ords/r/medimatrics/medimatrics/login"
  status = 200
  force = true

[[redirects]]
  from = "/skillsup/*"
  to = "https://oracleapex.com/ords/r/design_sparker/skills-up/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/skillsup"
  to = "https://oracleapex.com/ords/r/design_sparker/skills-up/login"
  status = 200
  force = true

[[redirects]]
  from = "/tips/*"
  to = "https://g086cd062cdff6a-apex.adb.ap-singapore-1.oraclecloudapps.com/ords/r/oracle/apex/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tips"
  to = "https://g086cd062cdff6a-apex.adb.ap-singapore-1.oraclecloudapps.com/ords/r/oracle/apex/login"
  status = 200
  force = true

[[redirects]]
  from = "/projects/*"
  to = "https://oraclerizwan.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/projects"
  to = "https://oraclerizwan.netlify.app"
  status = 200
  force = true

[functions]

  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[context]

  [context.production]

    [context.production.functions]

      [context.production.functions.emails]
      included_files = [
        "./emails/**"
      ]

  [context.main]

    [context.main.functions]

      [context.main.functions.emails]
      included_files = [
        "./emails/**"
      ]
